### PR TITLE
Fix a11y issues in button toggle component

### LINKED ISSUE #528: Fix a11y issues in button toggle component

### PR DESCRIPTION
**Pull request by fateeand**
### Validation rules:
Validated using Playwright accessibility tests, Lighthouse tool, and manual checks including keyboard tab navigation and screen reader testing.

[Full doc with rules](https://absacorp-my.sharepoint.com/:fl:/g/personal/andrei_fateev_absa_africa1/IQCXaIJSyyLNQJJuhWWI0FVpAVw6yjZ-O58HNmD5WymZTnk?e=wblvWh&nav=cz0lMkZwZXJzb25hbCUyRmFuZHJlaV9mYXRlZXZfYWJzYV9hZnJpY2ExJmQ9YiFwaGhlWkZVTzcwbThrWTNkRm5vNVZING9qaXA4SjNoUGs5WHNkUEYwcGhzUEdSZVhfeE5zVG9YcmtWX2xSU3V0JmY9MDFRWEJFUEZNWE5DQkZGU1pDWlZBSkUzVUZNV0VOQVZMSiZjPSUyRiZmbHVpZD0xJmE9TG9vcEFwcCZwPSU0MGZsdWlkeCUyRmxvb3AtcGFnZS1jb250YWluZXI%3D)

---

## State before:
| Component     | aria-roles | button-name | color-contrast |
|--------------|-----------|-------------|----------------|
| Button toggle | -         | ❌           | ❌              |

---

## State after:
| Component     | aria-roles | button-name | color-contrast |
|--------------|-----------|-------------|----------------|
| Button toggle | ✅         | ✅           | ✅              |

---

## Checklist

- [x] Keyboard Navigation
  All interactive elements are fully operable via keyboard only, including buttons, inputs, menus, dialogs, sliders, drag-and-drop, tree views, multi-selects, and composite widgets. No traps or dead ends.

- [x] Focus Management
  Focus is visible, logical, moves in predictable order, trapped where necessary (modals/popovers), and restored after closing. Focus is perceivable in all interactive widgets.

- [x] Semantics / ARIA
  - Semantic HTML is used correctly.
  - ARIA roles, states, and properties are applied only when needed.
  - All form fields, tables, and widgets (including autocomplete, tree selects, tree tables, drag-and-drop, sliders, and multi-selects) are properly labeled and accessible.

- [x] Color / Contrast
  - Text and interactive elements meet contrast requirements (≥4.5:1 normal text, ≥3:1 large text).
  - Focus and selection indicators are visually perceivable.
  - Color is not the only indicator of state.

- [x] Screen Reader / Assistive Technology
  - All content, labels, and dynamic updates are perceivable via screen readers.
  - Live regions announce status messages, alerts, modals, notifications, and dynamic changes.
  - Interactive widgets provide proper announcements of selection and updates.

- [x] Responsive & Zoom
  - Components function correctly and remain readable at all viewport sizes and up to 200% zoom, including mobile and touch devices.
  - Prefer em/rem units over px where scaling is required.

- [N/A] Error Handling
  - Errors are clearly identified visually and programmatically.
  - Form inputs use aria-describedby or aria-invalid for inline messages.
  - Instructions and suggestions are accessible.

- [N/A] Dynamic Content / Updates
  - Status updates, alerts, notifications, and modals use live regions.
  - Updates do not disrupt focus or user control unexpectedly.

- [x] Interaction Feedback / States
  - All interactive states (hover, focus, active, disabled, drag-and-drop, reordering, multi-select) are visually perceivable.

- [N/A] Authentication & Sensitive Actions
  - Inputs and actions involving sensitive data provide accessible instructions, feedback, and error messages.

- [x] Predictable & Controllable UI
  - Components behave consistently and predictably.
  - Popups, modals, autocomplete suggestions, drag-and-drop, and dynamic content allow user control.

---

### Additional changes:
- Fixing color contrast of placeholder in input-like component
- Fixing color contrast of disabled buttons
- Making autocomplete virtual dropdown scalable for any root font size
- Two new background colors are introduced:
`--cps-color-bg-disabled: #f7f7f7;`
`--cps-color-bg-disabled-selected: #d7d5d5;`
-  The colors `--cps-color-text-medium` and `--cps-color-text-dark` are now slightly darker to suffice color contrast in a few places

---

## Release notes:
- Fix a11y issues in button toggle component

### CODE REVIEW

File: projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.ts [hunk 1]
```diff
@@ -51,11 +52,17 @@ export type CpsButtonToggleOption = {
 })
 export class CpsButtonToggleComponent implements ControlValueAccessor, OnInit {
```
Comment (korel-san) [inline projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.ts]: @fateeand ngOnChanges is implemented but OnChanges isn't in the implements clause — could we add it for consistency?

File: projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.ts [hunk 2]
```diff
@@ -160,13 +169,38 @@ export class CpsButtonToggleComponent implements ControlValueAccessor, OnInit {
     if (this.multiple && !this._value) {
       this._value = [];
     }
-    this._setEqualWidths();
+    this._rootFontSizePx = parseFloat(
+      getComputedStyle(this.document.documentElement).fontSize || '16'
+    );
+    if (document?.fonts?.ready) {
```
Comment (korel-san) [inline projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.ts]: @fateeand Looks like document?.fonts?.ready uses the global document instead of the injected this.document — might cause issues in SSR, what do you think?

File: projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.ts
Comment (korel-san) [inline projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.ts:143]: @fateeand It seems like onChange fires twice per update — the setter triggers it, and then _updateValue calls it again. Could we bypass the setter in  _updateValue to avoid that?

File: projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.ts [hunk 3]
```diff
@@ -160,13 +169,38 @@ export class CpsButtonToggleComponent implements ControlValueAccessor, OnInit {
...
+      );
+    }
   }
 
   // eslint-disable-next-line @typescript-eslint/no-empty-function
   onChange = (event: any) => {};
   // eslint-disable-next-line @typescript-eslint/no-empty-function
   onTouched = () => {};
+  // eslint-disable-next-line @typescript-eslint/no-empty-function
+  setDisabledState(disabled: boolean) {}
```
Comment (korel-san) [inline projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.ts:206]: @fateeand setDisabledState is a no-op right now — does it make sense to wire it by default to this.disabled so that formControl.disable() reflects in the UI?

File: projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.ts [hunk 4]
```diff
@@ -160,13 +169,38 @@ export class CpsButtonToggleComponent implements ControlValueAccessor, OnInit {
     if (this.multiple && !this._value) {
       this._value = [];
     }
-    this._setEqualWidths();
+    this._rootFontSizePx = parseFloat(
+      getComputedStyle(this.document.documentElement).fontSize || '16'
+    );
+    if (document?.fonts?.ready) {
+      document.fonts.ready.then(() => this._setEqualWidths());
```
[the remark this answers is not in the document]
Comment (fateeand) [reply projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.ts]: good catch! fixed

File: projects/cps-ui-kit/src/lib/components/cps-select/cps-select.component.ts [hunk 5]
```diff
@@ -325,7 +325,7 @@ export class CpsSelectComponent
   isOpened = false;
   optionHighlightedIndex = -1;
 
-  virtualListHeight = 240;
+  virtualListHeight = 242;
   virtualScrollItemSize = 44;
```
[the remark this answers is not in the document]
Comment (fateeand) [reply projects/cps-ui-kit/src/lib/components/cps-select/cps-select.component.ts:330]: Will be done in the PR with a11y support for a `cps-select` component

File: projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.ts [hunk 6]
```diff
@@ -238,24 +272,27 @@ export class CpsButtonToggleComponent implements ControlValueAccessor, OnInit {
...
+        totalWidth += 16;
+        if (label) totalWidth += 8;
       }
-      this.renderer.removeChild(hiddenSpan, text);
+
+      const totalWidthRem = this._pxToRem(totalWidth);
+      this.largestButtonWidth = Math.max(
+        this.largestButtonWidth,
+        totalWidthRem
+      );
```
[the remark this answers is not in the document]
Comment (fateeand) [reply projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.ts]: fixed

File: projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.html [hunk 7]
```diff
@@ -1,6 +1,10 @@
 <div class="cps-btn-toggle">
   @if (label) {
-    <div class="cps-btn-toggle-label">
+    <div
+      class="cps-btn-toggle-label"
+      [ngClass]="{
+        disabled
+      }">
```
[the remark this answers is not in the document]
Comment (fateeand) [reply projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.html]: done

File: projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.html [hunk 8]
```diff
@@ -1,6 +1,10 @@
 <div class="cps-btn-toggle">
   @if (label) {
```
[the remark this answers is not in the document]
Comment (fateeand) [reply projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.html:2]: This behavior is consistent across all the components, so we need to update all of them to accommodate this change. This is outside the scope of this PR.

File: projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.html [hunk 9]
```diff
@@ -15,68 +19,58 @@
...
-  </span>
+    (click)="updateValueOnClick(option.value)"
+    [attr.aria-pressed]="
+      option.value | checkOptionSelected: value : multiple : true : ''
+    "
+    [attr.aria-label]="option.ariaLabel || option.label || null"
+    [style.min-width.rem]="equalWidths ? largestButtonWidth : null">
+    <span class="cps-btn-toggle-content-option-inner">
+      @if (option.icon) {
+        <cps-icon [ngClass]="{ 'me-2': !!option.label }" [icon]="option.icon">
```
[the remark this answers is not in the document]
Comment (fateeand) [reply projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.html]: done

File: projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.ts (hunk 1 above)
Comment (fateeand) [reply projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.ts]: thanks, fixed

File: projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.ts (hunk 2 above)
Comment (fateeand) [reply projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.ts]: Thanks, copilot also caught this. Fixed

File: projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.ts
Comment (fateeand) [reply projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.ts:143]: Fixed

File: projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.ts (hunk 3 above)
Comment (fateeand) [reply projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.ts:206]: No changes here. The `setDisabledState` function already existed - I just moved it next to the other no-op methods.

Afair, this was an intentional decision originally due to conflicts when using both `[formControl]` and `[disabled]` together. When `ctrl.disable()` is called, `setDisabledState(true)` would run and set `this.disabled = true`. However, on the next change detection cycle, `[disabled]="false"` would overwrite it, creating a conflict between reactive form state and input binding.

Making `setDisabledState` a no-op avoids having two competing sources of truth. The component treats `[disabled]` as a single source of truth. If consumer apps want to disable via reactive forms, they should explicitly bind `[disabled]="ctrl.disabled`.

**Review by korel-san — APPROVED** [review]
